apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfsoe
  namespace: default
spec:
  gitImplementation: go-git
  interval: 30s
  ref:
    tag: 6.3.3
  timeout: 60s
  url: https://github.com/stefanprodan/podinfo.git
